FESPfinal/EDUTUBE

package-lock.json
package.json
src/components/atom/Radio.tsx
tailwind.config.js

- 라디오 버튼 구현하였습니다.
<br>
<br>
- 현재 라디오 버튼 단일만 만들어 두었는데, 인터넷 서치를 하다보니 라이오 그룹이라는 컴포넌트를 하나더 만들어 가로정렬을 컨트롤 하는 것 같습니다. 그룹 컴포넌트를 만드는 것에 여러분의 의견을 듣고싶습니다.
close #6

[UI/6]: Radio atom 추가

---

src/components/atom/Input.tsx

- input atom 구현했습니다
<br>
<br>
- active는 유효성검사 통과한 경우에 때만 / isError가 'true'가 되면 border 색상과 helperTxt 표시됩니다
- dark 모드적용까지 했는데 저렇게 하면 되는지 atom작업은 처음이라 저렇게 하면 되는지 궁금합니다
close #3

[UI/3]: Input atom 구현

---

src/components/atom/Stepper.tsx

- Stepper atom 구현
<br>
<br>
- a태그로 만들어 title을 눌러 해당하는 곳으로 넘어가는 방식으로 했는데 어떠신가요?
- 상태는 default, active에서 error 상태 하나 추가했습니다(유효성 검사에서 걸리는 경우)
close #9

[UI/9]: Stepper atom 구현

---

package-lock.json
package.json
src/components/atom/PlusButton.tsx

- Plus button 기능 구현
- URL을 더 입력받을 수 있는  plus button 기능 
- + 버튼은 fontawesome이라는 곳에서 node modules 설치하여 추가하였습니다.
-  hover시 dark main color로 변하도록 구현하였습니다.
다들 아이콘 사용하실 때 
```import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPlus } from '@fortawesome/free-solid-svg-icons'; 
...
return(
<FontAwesomeIcon icon={faPlus} className="ml-4" />
)
```
<br>
이런식으로 사용하면 됩니다. 
[폰트어썸 링크](https://fontawesome.com/search?q=plus&o=r&m=free)
위 페이지에서 검색하셔서 가져오시면 됩니다.
-
<br>
-폰트어썸이 가장 많이 사용한다고 해서 임의로 폰트어썸 지정하고 아이콘 사용했습니다! 혹시 아이콘 사용하는 곳에 대해서 의견있으시면 의견주시면 감사하겠습니다 ~
close #13

[UI/13] Plus Button 구현

---

src/components/atom/RatingBar.tsx
src/components/atom/RatingBarGroup.tsx

- 후기 점수를 나타내는 RatingBar를 만들었습니다.
- 
- RatingBar라는 atom을 만들고, RatingBar x 5를 가진 RatingBarGroup이라는 atom 컴포넌트를 만들었습니다. 후기의 경우 항상 5개가 표시되기에 Group이라는 것을 만들어 사용하기 쉽게 하였습니다.
<br>
<br>
- percentList에 표시하고싶은 퍼센트 숫자를 입력하면 rating bar가 채워집니다.

[UI/14] Rating Bar atom 구현

---

src/components/atom/SliderButton.tsx

- 찜하기 등에서 카드 목록 옆으로 넘길 수 있는 버튼 구현하였습니다.
- left, right 값에 따라서 왼쪽 오른쪽 버튼이 되도록 구현하였습니다
- hover시 색상 변하게 구현하였습니다.
<br>
-
<br>
close #16

[UI/16] SliderButton 구현

---

src/components/atom/Tooltip.tsx

- 툴팁 기능 구현
- 다크모드/라이트모드 같은 색이 잘 보인다고 생각해서 별도의 색처리는 하지 않았습니다.
<br>
<br>
- 툴팁 사용법
```jsx
<Tooltip content="툴팁내용입니다.">
<i>tooltip</i>
</Tooltip>
```
- 툴팁이 필요한 컴포넌트 밖에 툴팁 컴포넌트를 감싸줍니다.
close #31

[UI/31]: Tooltip atom 구현

---

package-lock.json
package.json
src/helper/utils/ReactQueryClient.tsx

- ReactQueryClient 설정
<br>
-
<br>
- package.json / ReactQueryClient 설정

[Feat/45]: ReactQueryClient 설정

---

app/sign-up/layout.tsx
app/sign-up/page.tsx
package-lock.json
package.json
src/components/atom/Radio.tsx
src/components/views/sign-up/SignUp.tsx
src/components/views/sign-up/SignUpIdPw.tsx
src/components/views/sign-up/SignUpSellerInfo.tsx
src/components/views/sign-up/SignUpUserInfo.tsx
src/components/views/sign-up/consts.ts
src/components/views/sign-up/types.ts
src/queries/signUp/useCheckDuplicateEmail.ts
src/queries/signUp/useCreateUser.ts

- 일반회원/강사회원 회원가입을 구현하였습니다.
<br>
- 이메일과 비밀번호를 입력하는 화면입니다.
- 이메일 중복여부를 확인할 수 있습니다.
- validation check를 진행합니다.
- 다음 버튼을 누르면 프로필 등록할 수 있는 view가 나타납니다.
<br>
- 일반 회원 선택시 작성하는 프로필 목록입니다.
<br>
- 강사 회원 선택시 작성하는 프로필 목록입니다.
<br>
- 코드를 어떻게 하면 깔끔하게 작성할 수 있을까요...

[Feat/41] 일반회원/강사회원 회원가입 구현

---

app/login/layout.tsx
app/login/page.tsx
middleware.ts
package-lock.json
package.json
src/components/views/login/Login.tsx
src/components/views/sign-up/SignUpSellerInfo.tsx
src/components/views/sign-up/SignUpUserInfo.tsx
src/queries/login/useLogin.ts

- 로그인을 하면 토큰을 session cookie에 저장하는 기능을 구현하였습니다.
- 로그인에 성공하면 home으로 이동합니다.
<br>
<br>
- 일정 작업 이후 middleware를 사용하여 페이지 접근 권한 부여할 예정입니다.

[Feat/54]: 로그인 기능 구현

---

src/components/views/mypage/MypageMenu.tsx

Fix: 메뉴바 수정

---

src/components/atom/Button.tsx
src/components/views/coffeechat/CoffeechatLists.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/components/views/mypage/MypageMenu.tsx
src/components/views/mypage/purchase/PurchaseList.tsx
src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
src/queries/coffeechat/order/useUpdateOrder.tsx

[Hotfix/1]: 커피챗 페이지 데이터 추가 및 회원 정보 type에 따른 조건 렌더링

---

samples/dbinit.js

Data: dbinit data 추가

---

next.config.js
src/components/atom/ProfileImageUploader.tsx
src/components/views/mypage/MypageSellerInfo.tsx
src/components/views/mypage/MypageUserInfo.tsx
src/components/views/sign-up/SignUpSellerInfo.tsx
src/components/views/sign-up/SignUpUserInfo.tsx
src/helper/constants/apiConst.ts
src/helper/types/userInfoTypes.ts
src/queries/common/useCreateFile.ts
src/queries/signUp/useCreateUser.ts

- 회원가입 시 프로필 이미지 등록기능 구현
- 로그인 후 내 정보 프로필 사진 불러오기 기능 구현
<br>
<br>
- 현재 next/image 사용시 서버에서 불러오는 주소가 변경되어 사진이 불러와지지 않는 경우가 발생하고 있습니다. unoptimize={true}로 설정하여 이미지 최적화 과정을 임시로 막아 사진을 불러오게 하고 있습니다. 이 부분은 추후 더 나은 해결법을 찾아 수정해햐 할 것 같습니다.
close #90

[Feat/90]: 프로필 이미지 등록 및 불러오기 기능 추가

---

next.config.js
package-lock.json
package.json
src/components/atom/ProfileImageUploader.tsx
src/components/block/navbar/NavLogoutModal.tsx
src/components/views/login/Login.tsx
src/components/views/mypage/MypageInfo.tsx
src/components/views/mypage/MypageMenu.tsx
src/components/views/mypage/MypageSellerInfo.tsx
src/components/views/mypage/MypageUserInfo.tsx
src/components/views/sign-up/SignUp.tsx
src/components/views/sign-up/SignUpIdPw.tsx
src/components/views/sign-up/SignUpSellerInfo.tsx
src/components/views/sign-up/SignUpUserInfo.tsx
src/helper/constants/apiConst.ts
src/helper/types/userInfo.ts
src/helper/types/userInfoTypes.ts
src/helper/utils/useEdutubeAxios.ts
src/queries/auth/useRefreshToken.ts
src/queries/common/useCreateFile.ts
src/queries/login/useLogin.ts
src/queries/mypage/useSelectUserInfo.ts
src/queries/signUp/useCreateUser.ts
src/stores/auth.ts
src/stores/userInfo.ts

Dev -> Main

---

src/components/views/mypage/MypageSellerInfo.tsx
src/components/views/mypage/MypageUserInfo.tsx
src/components/views/sign-up/SignUpSellerInfo.tsx
src/helper/utils/useEdutubeAxios.ts
src/queries/mypage/useUpdateUserInfo.ts
src/queries/signUp/useCheckDuplicateEmail.ts
src/queries/signUp/useCreateUser.ts

- user, seller 내정보 수정 기능 구현했습니다.
<br>
<br>
- 추후 Nav 제외한 페이지 내에서 스크롤 하는 UX 구현할 예정입니다.

[Feat/100]: user, seller 내정보 수정 기능 구현

---

app/not-found.tsx
middleware.ts
src/queries/login/useLogin.ts

- 로그인 여부, user-type에 따른 페이지 접근 권한 설정하였습니다.
- 404 페이지 구현하였습니다.
<br>
- seller, user 권한에 따른 페이지 접근 제한
- 비로그인 상태일 때 로그인 시 접근 가능한 페이지에 대한 접근 제한
<br>
- 추후 코드관련 설명 진행하겠습니다.

[Feat/102]: 로그인 여부, user-type에 따른 페이지 접근 권한 설정 / 404 페이지 구현

---

src/components/atom/GroupButtons.tsx

- options로 넣어준 값을 토대로 여러 버튼을 생성해주고 선택하여 색상이 변경될 수 있도록 하는 기능 구현
- 각 버튼들 사이에 '|'를 넣을 수 있도록 하였습니다.
<br>
-
<br>
- 
close #20

[UI/20] GroupButtons 구현

---

package-lock.json
package.json
src/components/atom/Avatar.tsx
src/components/atom/Button.tsx
src/components/views/coffeechat/CoffeechatLists.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx

- extra data 작성자 profile, name 보여주기
- 중간 nav 구현(내용, 일정, 장소 클릭 시 해당 컨텐츠로 스크롤바로 이동)
- detail page 레이아웃 및 디자인 수정
<br>
-
<br>
close #111

[Feat/111] 상세페이지 extra data 보여주기 및 css 정리

---

src/components/views/coffeechat/regist/CoffeechatRegist.tsx
src/helper/types/tempProduct.ts
src/queries/coffeechat/tempUseCreateProduct.ts

- child product에 parent(기존에 parentsId값), type(coffeechat/video), depth:2 추가
- parent product에 depth:1 추가
<br>
-
```
{
"ok": 1,
"item": {
"_id": 100,
"mainImages": [
"/uploads/6y-nvLdrt.png"
],
"name": "열다섯번째 감자의 감자 사진",
"content": "예감 오리지널 말레이시아 팜유",
"price": 20000,
"shippingFees": 0,
"show": true,
"active": true,
"quantity": 2,
"extra": {
"intro": "예감 오리지널 말레이시아 팜유예감 오리지널 말레이시아 팜유예감 오리지널 말레이시아 팜유",
"place": "online",
"online": "줌",
"offline": "",
"datetimeList": [
{
"date": "2023-12-11T04:05:56.659Z",
"time": "2023-12-11T04:05:56.659Z"
},
{
"date": "2023-12-11T04:05:57.689Z",
"time": "2023-12-11T05:15:00.000Z"
}
],
"author": "서희짱",
"authorImage": "/uploads/w6PGo-wEN.JPG",
"type": "coffeechat",
"jobCategory": [
"프론트엔드"
],
"regionCategory": "서울",
"productType": "parents",
"depth": 1
}, …
```

[Feat/116] regist extra값 수정

---

src/components/views/coffeechat/regist/CoffeechatRegist.tsx
src/helper/types/tempProduct.ts
src/queries/coffeechat/tempUseCreateProduct.ts

[Hotfix/2] buyQuantity 속성 추가

---

src/components/views/coffeechat/info/CoffeechatInfo.tsx

Fix: error 코드 삭제

---

src/components/block/searchBar/SearchBar.tsx
src/components/views/mypage/myCoffechat/MypageMyCoffeechat.tsx
src/queries/mypage/myCoffeechat/useSelectSellerItemSearch.tsx

- 내가 등록한 커피챗 상품 제목 검색하는 기능 구현하였습니다.
<br>
<br>
-

[Feat/133]: 내가 등록한 커피챗 내에서 제목 검색기능 구현

---

src/components/atom/NextImage.tsx
src/components/views/coffeechat/CoffeechatLists.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/components/views/coffeechat/review/ReplyItem.tsx
src/components/views/mypage/cart/CartItem.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatItem.tsx
src/components/views/mypage/purchase/PurchaseCard.tsx
src/queries/coffeechat/review/useSelectReply.ts

- 상세페이지에서 해당 상품에 대한 후기 목록 구현
- nextImage 예외처리 추가 및 이름 변경
<br>
-
<br>
-
close #135

[Feat/135] 후기 상세 목록 기능 

---

src/components/atom/RatingStarGroup.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/components/views/coffeechat/review/RatingSummary.tsx

- 후기 전체 요약 컴포넌트 구현
<br>
-
<br>
- 
close #144

[Feat/144]: 후기 전체 요약 컴포넌트 

---

app/@modal/(.)coffeechat/info/[_id]/cart/page.tsx
src/components/views/coffeechat/info/CoffeechatCartModal.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/components/views/coffeechat/info/CoffeechatModal.tsx

- 상세페이지에서 장바구니 버튼 생성 및 기능 추가
- 예약하기에서 포인트 기능 추가
<br>
-
<br>
-
close #147

[Feat/147]: 장바구니 및 결제하기 포인트 기능 추가

---

app/coffeechat/page.tsx
app/page.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/queries/coffeechat/delete/useDeleteCoffeechat.tsx

- 삭제하기 기능 구현
- 
<br>
<br>
- 게시물 삭제는 된 상태인데 커피챗 리스트로 돌아왔을 때 데이터 Update가 잘 안되는  상황입니다. initData로 가져온 부분이라 어떻게 해야할지 감이 잘 안오네요!
close #155

[Feat/155] 삭제하기 기능 구현

---

src/components/block/navbar/NavLogoutModal.tsx
src/components/views/login/Login.tsx
src/helper/utils/useEdutubeAxios.ts
src/queries/coffeechat/useCreateProduct.ts
src/queries/coffeechat/useGetUserInfo.ts
src/queries/member/useSelectMemberInfo.ts
src/queries/member/useSelectMemberInfoExtra.ts

- 수정안되있던 axios edutubeAxios로 모두 변경 및 필요없는 cookie 제거하였습니다.
<br>
-
<br>
-
close #158

[Feat/158] : 수정안되있던 axios edutubeAxios로 모두 변경 및 필요없는 cookie 제거

---

src/components/views/coffeechat/info/CoffeechatModal.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailBody.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx

- 내 커피챗 목록 상세에서 구매자 이름에 강사 이름이 들어가고 있던 것을 구매자 닉네임으로 변경하였습니다.
<br>
<br>
-
close : #166

Fix: 주문 시 address name 추가 및 내 커피챗 구매자 이름 표시

---

.env.development.local
.env.production.local
app/default.tsx
app/not-found.tsx
src/components/atom/NextImage.tsx
src/components/atom/SkeletonBox.tsx
src/components/atom/SpinningPage.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetail.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailBody.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailChatButton.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
src/components/views/mypage/myCoffechat/MypageMyCoffeechat.tsx
src/components/views/mypage/purchase/PurchaseCard.tsx
src/components/views/mypage/purchase/PurchaseList.tsx
src/helper/utils/datetime.ts
src/queries/mypage/myCoffeechat/useSelectMyCoffeechatChatLink.tsx

- 채팅 버튼 활성화 및 렌더링 관련 이슈 수정하였습니다
- 셀러: 채팅방 생성 시 자동으로 버튼이 안바뀜
- 유저: 채팅 가능한 시간이 되어도 버튼 활성화가 안됨
- 스켈레톤 임시 적용
<br>
- 셀러: 채팅방 생성 시 자동으로 버튼이 안바뀜 수정
- 유저: 채팅 가능한 시간이 되어도 버튼 활성화가 안됨 수정
<br>
-

[Fix/169] 채팅 버튼 활성화 및 렌더링 관련 이슈 수정

---

src/components/block/navbar/NavLogoutModal.tsx
src/components/views/coffeechat/CoffeechatLists.tsx
src/components/views/coffeechat/info/CoffeechatCartModal.tsx
src/components/views/coffeechat/info/CoffeechatInfo.tsx
src/components/views/coffeechat/info/CoffeechatModal.tsx
src/components/views/login/Login.tsx
src/components/views/mypage/cart/Cart.tsx
src/components/views/mypage/cart/CartItem.tsx
src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
src/components/views/mypage/purchase/PurchaseCard.tsx
src/helper/utils/datetime.ts
src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
src/queries/common/useCreateFile.ts
src/queries/mypage/useUpdateUserInfo.ts
src/stores/cart.ts

- 커피챗 리스트 카드 정보 추가하였습니다.
- 장비구니 갯수 변경 로직 추가하였습니다.
<br>
<br>
- feat/164 pull 받아서 동작 테스트 부탁드리겠습니다!
- 마이페이지에서 장바구니 시연 후 홈으로 이동 시 fetch 에러의 유무를 확인해주시면 감사하겠습니다~

[Feat/164]:  장바구니 수량 체크 변경 및 커피챗 목록에서 카드 정보(온라인, 오프라인, 카테고리, 장소) 추가 

---

README.md

- README 수정
- 이미지, gif 추가전 확인
<br>
<br>
- 민경님까지 확인하시면 머지하도록 하겠습니다
close #170

[Docs/170]: README 수정

---

src/components/block/searchBar/SearchBar.tsx
src/components/views/coffeechat/CoffeechatItem.tsx
src/components/views/coffeechat/CoffeechatLists.tsx
src/queries/coffeechat/useSelectCoffeechatList.ts
src/queries/coffeechat/useSelectCoffeechatSearch.tsx

- 검색 기능 추가
- 검색 결과 없을시 안내문구 추가
<br>
-
<br>
- 배너 이미지 작업할 때 같이 이미지 없을 때 보여주는 이미지도 같이 추가할 예정입니다. 
- 검색어가 없을 경우 검색 클릭 했을 때 처음에 가져왔던 initData를 검색결과 리스트인 coffeechatSearchList에 setCoffeechatSearchList에다가 넣어주었는데,  이렇게 구성하는 것보다 더 괜찮은 방법이 있다면 답글 남겨주시면 감사하겠습니다! 
```javascript
const doSearch = () => {
if (searchTerm) {
searchMutate(searchTerm, {
onSuccess: (data) => {
setCoffeechatSearchList(data);
},
onError: error => { alert(`검색에 실패하였습니다 ${error.message}`) }
});
} else {
setCoffeechatSearchList(initData); // 이부분!
}
};
```
이렇게 작성했습니다.  
close #180

[Feat/180]: 커피챗 리스트에서 검색 기능 추가

---

src/components/block/searchBar/SearchBar.tsx
src/components/views/coffeechat/CoffeechatLists.tsx
src/helper/constants/categoryConst.ts

- 직무 카테고리별 필터링 기능 추가
- 지역 카테고리별 필터링 기능 추가
- 지역 카테고리 리스트 변경 (서울->서울시)
- 검색창 입력 text 컬러 흰색으로 나와서 글자 색상 안보이는 에러 처리 (다크모드 색상 지정)
<br>
-
<br>
-

[Feat/190]: 커피챗 리스트 카테고리별 필터링 기능 추가
